// Type: SendDataId
// Assembly: game, Version=1.0.4.1, Culture=neutral, PublicKeyToken=null
// MVID: D0F84B30-D7A0-41D8-8306-C72BB0D9D9CF
// Assembly location: C:\Users\DartPower\Downloads\Terraria.Xbox.360.Edition.XBLA.XBOX360-MoNGoLS\5841128F\000D0000\Terraria\Terraria.exe\ASSEMBLY.exe

internal enum SendDataId
{
  SERVER_REQ_LEAVE = 2,
  SERVER_REQ_PLAYER_INFO = 3,
  SERVER_WORLD_INFO = 7,
  SERVER_TILE_DATA_START = 9,
  SERVER_TILE_DATA = 10,
  SERVER_REQ_CHECK_TILE_DATA_IN_RANGE = 11,
  SERVER_PLAYER_SPAWNED = 12,
  SERVER_PLAYER_POSITION_CONTROLS_ITEM = 13,
  SERVER_PLAYER_ACTIVE = 14,
  SERVER_WORLD_ITEM_xx = 21,
  SERVER_WORLD_ITEM_yy = 22,
  SERVER_WORLD_NPC = 23,
  SERVER_REQ_PASSWORD = 37,
  SERVER_REQ_RELEASE_ITEM = 39,
  SERVER_WORLD_DONE = 49,
  SERVER_NPC_NAMES = 56,
  SERVER_GOOD_EVIL_STATUS = 57,
}
