// Type: Terraria.Leaderboards.Column
// Assembly: game, Version=1.0.4.1, Culture=neutral, PublicKeyToken=null
// MVID: D0F84B30-D7A0-41D8-8306-C72BB0D9D9CF
// Assembly location: C:\Users\DartPower\Downloads\Terraria.Xbox.360.Edition.XBLA.XBOX360-MoNGoLS\5841128F\000D0000\Terraria\Terraria.exe\ASSEMBLY.exe

namespace Terraria.Leaderboards
{
  public enum Column
  {
    AIR_COLUMN,
    GROUND_COLUMN,
    WATER_COLUMN,
    LAVA_COLUMN,
    ORE_COLUMN,
    GEMS_COLUMN,
    SOILS_COLUMN,
    WOOD_COLUMN,
    FURNITURE_COLUMN,
    TOOLS_COLUMN,
    WEAPONS_COLUMN,
    ARMOR_COLUMN,
    CONSUMABLES_COLUMN,
    MISC_COLUMN,
    POTIONS_COLUMN,
    LIGHTS_COLUMN,
    AMMO_COLUMN,
    SEEDS_COLUMN,
    KEYS_COLUMN,
    KING_SLIME_COLUMN,
    CTHULHU_COLUMN,
    EATER_COLUMN,
    SKELETRON_COLUMN,
    WALL_COLUMN,
    TWINS_COLUMN,
    SKELETRON_PRIME_COLUMN,
    DESTROYER_COLUMN,
    OCRAM_COLUMN,
    DROWNED_COLUMN,
    FALLEN_COLUMN,
    BURIED_COLUMN,
    BURNED_COLUMN,
    COLUMN_COUNT,
  }
}
