// Type: Terraria.HowToPlay.UI
// Assembly: game, Version=1.0.4.1, Culture=neutral, PublicKeyToken=null
// MVID: D0F84B30-D7A0-41D8-8306-C72BB0D9D9CF
// Assembly location: C:\Users\DartPower\Downloads\Terraria.Xbox.360.Edition.XBLA.XBOX360-MoNGoLS\5841128F\000D0000\Terraria\Terraria.exe\ASSEMBLY.exe

using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;
using System.Text;
using Terraria;

namespace Terraria.HowToPlay
{
  internal class UI
  {
    public static string[] HTP_TEXT_EN = new string[14]
    {
      "<i>BASICS:</i>\nDig! Fight! Explore! Build! In Terraria, every World is unique-from the floating islands in the sky to the deepest level of The Underworld. Adventure to the ends of the earth, and defeat villainous bosses along the way. The World is your canvas.\n\nChop down trees with an axe to gather wood. Kill slimes and collect their gels. Combine wood and gels to craft torches. When you explore caves, it helps to have wood platforms. Craft them out of wood.\n\nUse a pickaxe to mine the many types of ore in the world and smelt them into bars at a furnace. Use those to craft better weapons and armor. Some weapons, such as bows and guns, require ammo in your Ammo slots. Magic weapons require mana.\n\nKeep an eye out for Life Crystals to increase your health, and collect Falling Stars to craft Mana Crystals. Oh, and build a house before nightfall. You'll need it.",
      "<i>CHARACTER CREATION:</i>\nCreate a character and customize them any way you want!\n\nA character on the <i>Normal</i> difficulty setting only drops coins when killed. On <i>Difficult</i>, a character drops all their items. When a <i>Hardcore</i> character dies they are permanently deleted. This setting is only recommended for the most advanced (and HARDCORE) players.\n\nItems on a character, stay on that character. Items in a World, stay in that World.",
      "<i>CONTROLS:</i>\nUse " + (object) '\x0084' + " to move around. Press down to fall through wood platforms.\nPress " + (string) (object) '\x008C' + " to jump.\nPress " + (string) (object) '\x0081' + " to perform an action with the current item-such as swinging an axe, placing a torch, or drinking a potion.\nUse " + (string) (object) '\x0085' + " to aim your cursor.\nThere are two " + (string) (object) '\x0085' + " Cursor Modes. Press " + (string) (object) '\x008F' + " to switch between them.\n1) In Auto Mode, pressing " + (string) (object) '\x0081' + " performs an action in the direction of the cursor.\n2) In Manual Mode, the cursor acts like a mouse.\nPressing " + (string) (object) '\x0081' + " performs an action on the cursor's exact location.\nPress " + (string) (object) '\x008D' + " to use a nearby object or NPC. Usable objects and NPCs are highlighted in yellow; when you are near, they will flash and you can interact with them.\nPress " + (string) (object) '\x008A' + " to drop the current item.\nAim and press " + (string) (object) '\x0080' + " to use a grappling hook or similar item (if you have one in your Inventory).\nYou can press " + (string) (object) '\x008E' + " as an alternate jump button.\nAdvanced players may wish to switch the grappling and alternate jump buttons; you can do this from the Controls Menu.\nPress " + (string) (object) '\x0087' + " to view the World Map and player list.",
      "<i>HUD:</i>\nThe <i>Inventory Bar</i> is at the top of your screen. The current item is highlighted in yellow. You can scroll between items by pressing \x0082\x0083.\n\nTo rearrange items or view the rest of your Inventory, press " + (object) '\x008B' + ".\nYour health is also at the top of your screen. Every heart is 20 health. If you are underwater, your remaining breath is shown below your health. If you have mana, it will appear as blue star icons on the right side of your screen. Every star is 20 mana.\n\nAny active buffs or debuffs-along with their remaining duration-are shown below the Inventory Bar. To cancel a buff or find out more about it go to the Equip section of the Inventory Menu.",
      "<i>INVENTORY:</i>\nPress " + (object) '\x008B' + " to access the Inventory Menu. The Inventory Menu contains several sections: Inventory, Equip, Crafting, and Housing. If you have activated a chest or vendor NPC, there will be a section for it as well.\n\nSwitch between sections by pressing \x0082\x0083. The Inventory Bar is the top row of item slots in your Inventory. Use " + (string) (object) '\x0084' + " to move between slots. Press " + (string) (object) '\x008C' + " to pick up an item; if there is a stack of items in the slot then " + (string) (object) '\x008C' + " will pick them all up. Press " + (string) (object) '\x0081' + " to pick up a single item. Move to another slot and press " + (string) (object) '\x008C' + " to place the item you picked up.\n\nWhen you pick up an item you can switch between the Equip and Inventory sections-or to a chest (or other storage) section-and the item will remain on your cursor.\nPress " + (string) (object) '\x008A' + " to move an item directly to the Trash. An item in the Trash slot will be deleted after a brief delay. Press " + (string) (object) '\x0081' + " to equip items such as armor or accessories directly to a usable slot.",
      "<i>EQUIP:</i>\nThe Equip section of the Inventory Menu contains slots for armor items, vanity items, accessory items, and buffs/debuffs.\nUse " + (object) '\x0084' + " to move between slots. Items in Vanity slots appear on your character but do not provide any stat bonuses or effects.\n\nPress " + (string) (object) '\x008C' + " to pick up and place items. You can pick up an item and switch between the Equip and Inventory sections and the item will remain on your cursor.\n\nActive buff/debuff slots are above your character avatar. Select an active buff or debuff to find out more about it.\nPress " + (string) (object) '\x008C' + " to cancel a buff; debuffs cannot be cancelled.",
      "<i>CRAFTING:</i>\nIn the Crafting section you can create new types of items by combining items in your Inventory as ingredients. The Crafting section is part of the Inventory Menu that can be opened by pressing " + (object) '\x008B' + ". Switch to the Crafting section by pressing \x0082\x0083.\n\nSwitch between item categories by pressing " + (string) (object) '\x0080' + " " + (string) (object) '\x0081' + ". There are six categories: Structures, Tools, Weapons, Armor, Consumables, and Miscellaneous.\n\nUse " + (string) (object) '\x0084' + " to scroll between crafting recipes. Press " + (string) (object) '\x008C' + " to craft an item from a crafting recipe and place it in your Inventory. Item recipes are shown in the vertical list. Any variations of that base item are shown in a horizontal list.\n\nMore crafting recipes will unlock as you gather exotic ingredients or create new crafting station items (such as a crafting table or anvil). Press " + (string) (object) '\x008A' + " to switch between showing only recipes you can currently craft, or showing all the recipes you have unlocked.\n\nIngredients for the current recipe are shown in the Ingredients area, along with any crafting station items that must be nearby in the World to craft the recipe. Press " + (string) (object) '\x008B' + " to enter (or exit) the Ingredients area to find out more about individual ingredients.",
      "<i>HOUSING:</i>\n\nBuild a house before nightfall to stay safe.\nA house (or room) is considered <i>valid</i> if it has side walls that are at least 6 blocks high, and a floor and ceiling at least 10 blocks wide. Additionally, the background must be entirely paneled with walls (such as wood walls or dirt walls). Finally, you must place a light source (such as a torch) and place both a chair and a table.\n\nYou can change your spawn point by placing and using a bed. If you find a Magic Mirror, you can use it to teleport back to your spawn point. As you progress, NPCs will move into your house if there are valid, empty rooms available to live in.\n\nThere is a Housing section in the Inventory Menu where you can manage your household. Open the Inventory Menu by pressing " + (object) '\x008B' + ", and press \x0082\x0083 to switch to the Housing section.\n\nIn the Housing section you can view the NPCs living in your rooms. Press " + (string) (object) '\x0084' + " to select different NPCs and find out about them. Press " + (string) (object) '\x008C' + " to assign that NPC to the room you are standing in. Press " + (string) (object) '\x008B' + " to show or hide NPC room flags in the World. Press " + (string) (object) '\x008A' + " to check if you are standing in valid housing.",
      "<i>STORAGE & VENDORS:</i>\n\nIf you use a storage item in the World (such as a chest) or a vendor NPC (such as a Merchant), it will open a special section in the Inventory Menu. In a storage item section, press " + (object) '\x008C' + " to pick up and place items. You can pick up an item and switch between the Inventory, Equip, and storage sections and the item will remain on your cursor.\n\nThere are also three storage shortcuts available: <i>Loot All</i> moves as many items as possible into your Inventory; <i>Deposit All</i> moves as many items as possible from your Inventory into the storage; <i>Quick Stack</i> moves only items from your Inventory that match item stacks already in the storage.\n\nIn a vendor item section, press " + (string) (object) '\x008C' + " to purchase an item with coins. Move items from your Inventory into the vendor item section to sell them.",
      "<i>BUFFS & DEBUFFS:</i>\nBuffs are positive status effects such as Invisibility or a pet.\nDebuffs are negative status effects such as Bleeding or Potion Sickness.\n\nActive buffs and debuffs are shown below your Inventory Bar. Most have a limited duration.\n\nYou can find out more about them in the Equip section of the Inventory Menu. From there, you can also cancel a buff by selecting it and pressing " + (object) '\x008C' + "; debuffs cannot be cancelled.",
      "<i>MULTIPLAYER:</i>\nTerraria is a multiplayer game by default.\nSplit-screen supports up to 4 players. Local players can join your game by attaching controllers and pressing " + (object) '\x0088' + " or " + (string) (object) '\x008C' + " at any time. Online games support up to 8 players.\n\nWhen you start an online game, the game will be visible to your friends (unless you've selected Invite Only). Likewise, when your friends host public games they will be visible for you to join.\n\nWhile in a game, press " + (string) (object) '\x0087' + " to view a list of players and their locations in the World Map. From here you can also invite players, view Gamer Cards, toggle your Player vs. Player (PvP) mode, or choose your team color.\n\nPlayers who activate Player vs. Player (PvP) mode can attack each other. When players select a team color their location and health are only visible to teammates. Teammates cannot attack each other.",
      "<i>DUNGEON:</i>\nEvery World contains a Dungeon.\nDo not enter the Dungeon without first defeating its guardian.\nLook for an Old Man, and speak to him at night.\nBe prepared.",
      "<i>HARD MODE:</i>\nTo activate Hard Mode, you must defeat the unspeakable horror that lives in The Underworld. Find a Guide Voodoo Doll and hurl it into the infernal lava to summon the monstrosity.\n\nIf you defeat it, use its treasure to destroy Demon Altars. Hard Mode permanently changes the World: new environments appear, as do new enemies, bosses, items, and NPCs.\n\nHard Mode is only for the bravest warriors.",
      "<i>BANNING WORLDS:</i>\nIf you find offensive content in another player's World, you can choose to add that World to your Banned World List. To do this, enter the Pause Menu and press " + (object) '\x0083' + ". If you attempt to join that World in the future, you will be notified that it is in your Banned World List and given the option to either remove it from the list and continue into the World or to back out."
    };
    public static string[] HTP_TEXT_DE = new string[14]
    {
      "<i>GRUNDLAGEN:</i>\n\nGraben! Kämpfen! Erkunden! Bauen! In Terraria ist jede Welt einzigartig -- von den schwimmenden Inseln am Himmel bis zu den tiefsten Ebenen der Unterwelt. Wage dich bis zum Ende der Erde und besiege auf dem Weg bösartige Endgegner. Die Welt ist deine Leinwand.\n\n Fälle Bäume mit einer Axt, um Holz zu sammeln. Töte Schleime und sammle ihre Gels. Kombiniere Holz und Gel, um Fackeln anzufertigen. \n\nWenn du Höhlen erforschst, ist es hilfreich, hölzerne Plattformen zu haben. Fertige sie aus Holz an.\n\nVerwende eine Spitzhacke, um die verschiedenen Erze in der Welt abzubauen und schmelze sie in einem Schmelzofen zu Barren. Verwende diese, um bessere Waffen und Rüstung herzustellen. Manche Waffen, wie Bögen und Pistolen, benötigen Munition in deinen Munitions-Slots. Magische Waffen benötigen Mana.\n\nHalte die Augen auf nach Lebenskristallen, um deine Gesundheit zu erhöhen, und sammle Sternschnuppen, um Manakristalle herzustellen.\n\nOh, und baue ein Haus vor Einbruch der Dunkelheit. Du wirst es brauchen.",
      "<i>CHARAKTERERSTELLUNG:</i>\n\nErstelle einen Charakter und gestalte ihn so, wie du ihn dir vorstellst!\n\nEin Charakter der Schwierigkeitsstufe <i>Normal</i> verliert nur seine Münzen, wenn er stirbt. Bei der Einstellung <i>Schwer</i> verliert ein Charakter alle Gegenstände. Wenn ein<i>Hardcore</i>-Charakter stirbt, wird er für immer gelöscht. Diese Schwierigkeitsstufe ist nur für fortgeschrittene (und HARDCORE-) Spieler gedacht.\n\nGegenstände, die ein Charakter besitzt, bleiben dem Charakter erhalten. Die Gegenstände einer Welt bleiben in dieser Welt.",
      "<i>STEUERUNG:</i>\n\nBewege dich mit " + (object) '\x0084' + ". Drücke Unten, um durch hölzerne Plattformen zu fallen.\n\nDrücke zum Springen " + (string) (object) '\x008C' + ".\n\nDrücke " + (string) (object) '\x0081' + ", um eine Aktion mit einem Gegenstand auszuführen, wie z.B. eine Axt schwingen, eine Fackel platzieren oder einen Trank trinken.\n\nBenutze " + (string) (object) '\x0085' + ", um mit dem Cursor zu zielen. Es gibt zwei Cursor-Modi " + (string) (object) '\x0085' + ". Drücke " + (string) (object) '\x008F' + ", um zwischen ihnen zu wechseln.\n\n1) Im Auto-Modus wird durch Drücken von " + (string) (object) '\x0081' + " eine Aktion in die Richtung des Cursors ausgeführt.\n\n2) Im manuellen Modus agiert der Cursor wie eine Maus. Durch Drücken von " + (string) (object) '\x0081' + " wird eine Aktion an der Position des Cursor ausgeführt.\n\nDrücke " + (string) (object) '\x008D' + ", um ein nahegelegenes Objekt oder einen NPC zu benutzen. Benutzbare Gegenstände und NPCs leuchten gelb. Wenn du in der Nähe bist, beginnen sie zu leuchten und du kannst mit ihnen interagieren.\n\nDrücke " + (string) (object) '\x008A' + ", um einen Gegenstand fallen zu lassen.\n\nZiele und drücke " + (string) (object) '\x0080' + ", um einen Enterhaken oder Ähnliches zu benutzen (falls du einen in deinem Inventar hast).\n\nDu kannst " + (string) (object) '\x008E' + " als alternativen Knopf zum Springen drücken. Fortgeschrittene Spieler wollen vielleicht die Knöpfe für Festhaken und Springen tauschen. Das ist im Steuerungsmenü möglich.\n\nDrücke " + (string) (object) '\x0087' + ", um Weltkarte und Spielerliste zu sehen.",
      "<i>HUD:</i>\n\nDie <i>Inventarleiste</i> befindet sich oben auf dem Bildschirm. Der aktuelle Gegenstand ist gelb markiert. Durch Drücken von \x0082\x0083 kannst du zwischen Gegenständen wechseln. Drücke " + (object) '\x008B' + ", um Gegenstände neu zu arrangieren oder den Rest des Inventars zu betrachten.\n\nDeine Lebenspunkte werden ebenfalls oben auf dem Bildschirm angezeigt. Jedes Herz steht für 20 Lebenspunkte.\n\nBist du unter Wasser, wird die verbleibende Atemluft unter deinen Lebenspunkten angezeigt.\n\nMana erkennst du als blaue Sterne auf der rechten Bildschirmseite. Jeder Stern steht für 20 Mana.\n\nAktive Buffs und Debuffs werden -- mit der verbleibenden Zeit -- unter der Inventarleiste angezeigt. Wechsle in die Ausrüstungssektion des Inventarmenüs, um einen Buff abzuschalten oder mehr über ihn herauszufinden.",
      "<i>INVENTAR:</i>\n\nDrücke " + (object) '\x008B' + ", um das Inventarmenü zu öffnen.\n\nDas Inventarmenü enthält verschiedene Sektionen: Inventar, Ausrüstung, Herstellung und Unterkunft. Wenn du eine Schatzkiste oder einen Verkäufer-NPC aktiviert hast, wird dafür auch eine Sektion angezeigt.\n\nWechsle zwischen den Sektionen, indem du \x0082\x0083 drückst.\n\nDie Inventarleiste ist die obere Reihe der Gegenstand-Slots in deinem Inventar.\n\nDrücke " + (string) (object) '\x0084' + ", um zwischen den Slots zu wechseln.\n\nDrücke " + (string) (object) '\x008C' + ", um einen Gegenstand aufzuheben. Falls sich ein Stapel an Gegenständen im Slot befindet, hebst du sie mit " + (string) (object) '\x008C' + " alle auf. Drücke " + (string) (object) '\x0081' + ", um einen einzelnen Gegenstand aufzuheben.\n\nWähle einen anderen Slot und drücke " + (string) (object) '\x008C' + ", um den Gegenstand dort abzulegen.\n\nWenn du einen Gegenstand aufhebst, kannst du zwischen den Ausrüstungs- und Inventar-Sektionen -- oder zu einer Schatzkisten- (oder einer anderen Lagerungs-) Sektion -- wechseln und der Gegenstand wird auf deinem Cursor bleiben.\n\nDrücke " + (string) (object) '\x008A' + ", um einen Gegenstand direkt in den Müll zu werfen.\n\nEin Gegenstand im Müll-Slot wird nach einer kurzen Verzögerung gelöscht. Drücke " + (string) (object) '\x0081' + ", um Gegenstände wie Rüstung oder Zubehör direkt in einem verwendbaren Slot zu platzieren.",
      "<i>AUSRÜSTUNG:</i>\n\nDie Ausrüstungs-Sektion des Inventarmenüs enthält Slots für Rüstung, Verzierung, Zubehör und Buffs/Debuffs.\n\nDrücke " + (object) '\x0084' + ", um zwischen Slots zu wechseln.\n\nGegenstände in Verzierungs-Slots erscheinen an deinem Charakter, haben aber keine Wirkung und verleihen dir keine Boni.\n\nDrücke " + (string) (object) '\x008C' + ", um Gegenstände aufzunehmen und zu platzieren. Du kannst einen Gegenstand aufnehmen und zwischen den Ausrüstungs- und Inventarsektionen verschieben, wobei der Gegenstand auf deinem Cursor bleibt.\n\nAktive Buff-/Debuff-Slots befinden sich über deinem Charakter-Avatar. Wähle einen aktiven Buff oder Debuff, um mehr darüber zu erfahren. Drücke " + (string) (object) '\x008C' + ", um einen Buff abzubrechen; Debuffs können nicht abgebrochen werden.",
      "<i>HERSTELLUNG:</i>\n\nIn der Herstellungssektion kannst du neue Arten von Gegenständen herstellen, indem du Gegenstände aus deinem Inventar kombinierst.\n\nDie Herstellungssektion ist Teil des Inventarmenüs. Man öffnet es durch Drücken von " + (object) '\x008B' + ". Wechsle durch Drücken von \x0082\x0083 zur Herstellungssektion.\n\nWechsle zwischen den Gegenstandskategorien, indem du " + (string) (object) '\x0080' + ", " + (string) (object) '\x0081' + " drückst. Es gibt sechs Kategorien: Bauwerke, Werkzeuge, Waffen, Rüstung, Verbrauchsgegenstände und Verschiedenes.\n\nVerwende " + (string) (object) '\x0084' + ", um zwischen den Anleitungen zu wechseln.\n\nDrücke " + (string) (object) '\x008C' + ", um einen Gegenstand nach einer Anleitung herzustellen und platziere ihn in deinem Inventar.\n\nDie Anleitungen werden in der vertikalen Liste angezeigt. Sämtliche Variationen dieses Basisgegenstands werden in einer horizontalen Liste angezeigt. Du kannst mehr Anleitungen freischalten, indem du exotische Zutaten sammelst oder neue Geräte zur Herstellung produzierst (wie etwa eine Werkbank oder einen Amboss). Drücke " + (string) (object) '\x008A' + ", um entweder die Anleitungen anzuzeigen, mit denen du momentan etwas herstellen kannst, oder um sämtliche freigeschalteten Anleitungen anzuzeigen.\n\nBestandteile für die aktuelle Anleitung werden in der Bestandteilssektion angezeigt, zusammen mit den Geräten zur Herstellung, die sich in dieser Welt in der Nähe befinden müssen, um die Anleitung befolgen zu können. Drücke " + (string) (object) '\x008B' + ", um die Bestandteilssektion zu betreten (oder verlassen) und mehr über individuelle Bestandteile herauszufinden.",
      "<i>UNTERKUNFT:</i>\n\nBaue ein Haus vor Einbruch der Dunkelheit, um sicher zu sein.\n\nEin Haus (oder Zimmer) gilt als <i>fertig</i>, wenn die Seitenwände mindestens sechs Block hoch und Decke und Fußboden mindestens zehn Block breit sind. Außerdem muss die Rückseite komplett mit Wänden vertäfelt sein (wie z.B. mit Holzwänden oder Lehmwänden). Zum Abschluss musst du eine Lichtquelle (z.B. eine Fackel), einen Stuhl und einen Tisch aufstellen.\n\nDu kannst deinen Spawnpunkt ändern, indem du ein Bett platzierst und benutzt. Wenn du einen Magischen Spiegel findest, kannst du dich damit zu deinem Spawnpunkt teleportieren.\n\nJe weiter du vorankommst, desto mehr NPCs können in dein Haus einziehen, sofern du genug bewohnbare Räume für sie hast.\n\nIm Inventarmenü befindet sich eine Unterkunftssektion, in der du deinen Haushalt verwalten kannst. Öffne das Inventarmenü, indem du " + (object) '\x008B' + " drückst und wechsle mit \x0082\x0083 zwischen den Unterkunftssektionen.\n\nIn der Unterkunftssektion werden die NPCs angezeigt, die in deinen Räumen leben. Wähle mit " + (string) (object) '\x0084' + " verschiedene NPCs aus und du erfährst mehr über sie. Weise einem NPC mit " + (string) (object) '\x008C' + " den Raum zu, in dem du dich befindest. Lass dir mit " + (string) (object) '\x008B' + " die Standorte der NPCs in der Welt anzeigen oder blende sie aus. Drücke " + (string) (object) '\x008A' + ", um zu prüfen, ob du in einem fertigen Haus bist.",
      "<i>LAGERN & VERKÄUFER:</i>\n\nWenn du einen Lagergegenstand in der Welt (z.B. eine Kiste) oder einen Verkäufer-NPC (z.B. einen Händler) benutzt, öffnet sich eine spezielle Sektion des Inventarmenüs.\n\nDrücke " + (object) '\x008C' + " in der Lagersektion, um Gegenstände auszuwählen und zu platzieren. Du kannst einen Gegenstand aufheben und zwischen den Inventar-, Ausrüstungs- und Lagersektionen verschieben, wobei der Gegenstand auf deinem Cursor verbleibt.\n\nEs gibt drei Abkürzungen zur Lagerung: <i>Alles plündern<i> platziert so viele Gegenstände in deinem Inventar wie möglich; <i>Alles lagern</i> platziert so viele Gegenstände deines Inventars im Lager wie möglich;</i>Schnell stapeln</i> platziert nur Gegenstände von deinem Inventar im Lager, von denen dort bereits Stapel existieren.\n\nDrücke " + (string) (object) '\x008C' + " in der Gegenstandssektion eines Verkäufers, um einen Gegenstand mit Münzen zu kaufen. Platziere Gegenstände von deinem Inventar in der Gegenstandssektion des Verkäufers, um sie zu verkaufen.",
      "<i>BUFFS & DEBUFFS:</i>\n\nBuffs sind positive Statuseffekte, wie z.B. Unsichtbarkeit oder ein Haustier. Debuffs sind negative Statuseffekte, wie z.B. Verwundungen oder durch Tränke hervorgerufene Krankheiten.\n\nAktive Buffs und Debuffs werden unterhalb der Inventarleiste angezeigt. Die meisten haben eine zeitlich begrenzte Wirkung. In der Ausrüstungssektion des Inventarmenüs erfährst du mehr darüber. Dort kannst du Buffs auch deaktivieren, indem du sie auswählst und " + (object) '\x008C' + " drückst.",
      "<i>MEHRSPIELER:</i>\n\nTerraria ist automatisch ein Spiel für mehrere Spieler.\n\nDer geteilte Bildschirm unterstützt bis zu vier Spieler. Lokale Spieler können jederzeit deinem Spiel beitreten, indem sie Controller anschließen und " + (object) '\x0088' + " oder " + (string) (object) '\x008C' + " drücken.\n\nOnline-Spiele unterstützen bis zu acht Spieler. Wenn du ein Online-Spiel startest, wird das Spiel für deine Freunde sichtbar  (es sei denn, du hast \"Nur mit Einladung\" ausgewählt). Ebenso wird ein Spiel für dich sichtbar, wenn deine Freunde ein öffentliches Spiel starten.\n\nDrücke " + (string) (object) '\x0087' + " Im Spiel, um eine Liste der Spieler und ihre Positionen auf der Weltkarte anzuzeigen. Hier kannst du auch Spieler einladen, Spielerkarten betrachten, den Spieler-gegen-Spieler-Modus (PvP) aktivieren oder eine Farbe für dein Team auswählen.\n\nIm Spieler-gegen-Spieler-Modus (PvP) können Spieler sich gegenseitig angreifen.\n\nWenn Spieler eine Farbe für ihr Team auswählen, sind ihr Standort und ihre Gesundheit nur für Teammitglieder sichtbar. Teammitglieder können sich nicht gegenseitig angreifen.",
      "<i>KERKER:</i>\n\nIn jeder Welt gibt es einen Kerker.\n\nBetritt niemals einen Kerker, ohne zuerst seinen Wächter zu besiegen.\n\nSuche nach einem alten Mann und sprich mit ihm, wenn es Nacht ist.\n\nSei auf alles vorbereitet.",
      "<i>SCHWIERIGER MODUS:</i>\n\nUm den schwierigen Modus zu aktivieren, musst du das unsägliche Grauen besiegen, das in der Unterwelt lebt. Finde eine Führer-Voodoopuppe und wirf sie in die höllische Lava, um die Monstrosität herbeizurufen.\n\nWenn du sie besiegst, kannst du mit ihren Schätzen die Dämonenaltäre zerstören.\n\nDer schwierige Modus verändert die Welt dauerhaft: Es erscheinen neue Umgebungen, neue Feinde, Endgegner, Gegenstände und NPCs.\n\nDer schwierige Modus ist nur für die furchtlosesten Kämpfer gedacht.",
      "<i>WELTEN VERBANNEN:</i>\n\nWenn du anstößige Inhalte in der Welt eines anderen Spielers findet, hast du die Möglichkeit, diese Welt auf die \"Verbannte Welten\" Liste zu stellen. Dafür musst du das Pausenmenü aufrufen und " + (object) '\x0083' + " drücken. Solltest du zukünftig versuchen, diese Welt zu betreten, erhältst du eine Benachrichtigung, dass sich diese Welt auf der Liste deiner verbannten Welten befindet. Du kannst dann entscheiden, ob du die Welt aus dieser Liste streichen möchtest und damit weiteren Zugang zu ihr erhältst, oder ob der Bann weiterhin bestehen soll."
    };
    public static string[] HTP_TEXT_FR = new string[14]
    {
      "<i>LES BASES</i>\n\nCreusez ! Combattez ! Explorez ! Construisez ! Dans Terraria, chaque monde est unique : des îles flottantes dans le ciel aux profondeurs du monde des Enfers. Aventurez-vous jusqu'aux confins de la terre et réduisez à néant les boss qui croisent votre chemin. Le monde est votre toile.\n\nCoupez des arbres avec une hache pour collecter du bois. Éliminez des slimes pour récolter leur gel. Combinez le bois et le gel pour fabriquer des torches.\n\nLes plateformes en bois sont utiles lorsque vous explorez des grottes. Fabriquez-les avec le bois collecté.\n\n Extrayez tous les types de minerais du monde à l'aide d'une pioche et fondez-les en lingots aux fournaises. Avec ceux-ci, vous pourrez fabriquer de meilleures armes et armures. Vous aurez besoin de stocker des munitions pour certaines armes, telles que les arcs ou les pistolets. Les armes magiques ont besoin de mana.\n\nRestez à l'affût des Cristaux de Vie pour restaurer votre santé, et collectez les Étoiles filantes pour fabriquer les Cristaux Mana.\n\nPensez également à construire une maison avant la tombée de la nuit. Vous en aurez besoin.",
      "<i>CRÉATION DE PERSONNAGE</i>\n\nCréez un personnage et personnalisez-le à votre idée !\n\nEn mode <i>Normal</i>, un personnage ne perd ses pièces que quand il meurt. En mode <i>Difficile</i>, un personnage perd tous ses objets. Lorsqu'un personnage meurt en mode <i>Hardcore</i>, il est supprimé définitivement. Cette fonction est recommandée uniquement aux joueurs les plus expérimentés (et HARDCORE).\n\nLes objets que possède le personnage restent siens. Les objets d'un monde restent dans ce monde.",
      "<i>COMMANDES</i>\n\nUtilisez " + (object) '\x0084' + " pour vous déplacer. Appuyez sur Bas pour passer au travers des plateformes en bois.\n\nAppuyez sur " + (string) (object) '\x008C' + " pour sauter.\n\nAppuyez sur " + (string) (object) '\x0081' + " pour effectuer une action avec l'objet tenu (comme brandir une hache, placer une torche ou boire une potion).\n\nUtilisez " + (string) (object) '\x0085' + " pour viser avec votre curseur. Il y a deux modes Curseur " + (string) (object) '\x0085' + ". Appuyez sur " + (string) (object) '\x008F' + " pour passer de l'un à l'autre.\n\n1)En mode Auto, appuyer sur " + (string) (object) '\x0081' + " effectue une action dans la direction du curseur.\n\n2) En mode Manuel, le curseur agit comme une souris. Appuyer sur " + (string) (object) '\x0081' + " effectue une action à l'emplacement exact du curseur.\n\nAppuyez sur " + (string) (object) '\x008D' + " pour utiliser un objet ou un PNJ à proximité. Les objets et PNJ utilisables apparaissent en jaune ; ils se mettent à clignoter lorsque vous vous en approchez et vous pouvez interagir avec.\n\nAppuyez sur " + (string) (object) '\x008A' + " pour lâcher l'objet tenu.\n\nVisez et appuyez sur " + (string) (object) '\x0080' + " pour utiliser un grappin ou un objet similaire (si vous en avez un dans votre inventaire).\n\n " + (string) (object) '\x008E' + " est un autre bouton qui vous permet de sauter. Les joueurs expérimentés souhaiteront peut-être échanger le grappin contre des boutons de saut ; ceci est possible depuis le menu Commandes.\n\nAppuyez sur " + (string) (object) '\x0087' + " pour consulter la Carte du monde et la liste des joueurs.",
      "<i>Affichage tête haute</i>\n\nLa <i>barre d'inventaire</i> se trouve en haut de votre écran. L'objet tenu est surligné en jaune. Vous pouvez faire défiler les objets en appuyant sur \x0082\x0083. Pour réorganiser vos objets ou voir le reste de votre inventaire, appuyez sur " + (object) '\x008B' + ".\n\nVotre indicateur de santé se trouve également en haut de votre écran. Chacun des cœurs vous donne 20 points de santé.\n\nSi vous êtes sous l'eau, l'oxygène restant est affiché sous l'indicateur de santé.\n\nSi vous avez du mana, il apparaîtra sous forme d'étoiles bleues à la droite de votre écran. Chaque étoile représente 20 points de mana.\n\nTout buff ou débuff actif, ainsi que leur durée restante, sont affichés sous la barre d'inventaire. Pour annuler un buff ou en savoir plus à son sujet, consulter la section Équiper du menu Inventaire.",
      "<i>INVENTAIRE</i>\n\nAppuyez sur " + (object) '\x008B' + " pour accéder au menu Inventaire.\n\nLe menu Inventaire contient plusieurs sections : Inventaire, Équiper, Artisanat et Logement. Vous pourrez également trouver une section pour les coffres et PNJ vendeurs au cas où vous en auriez activés.\n\nChangez de sections en appuyant sur \x0082\x0083.\n\nLa barre d'inventaire représente la ligne supérieure des emplacements pour objets de votre inventaire.\n\nUtilisez " + (string) (object) '\x0084' + " pour vous déplacer dans les emplacements.\n\nAppuyez sur " + (string) (object) '\x008C' + " pour prendre un objet. Si il y a une pile d'objets dans l'emplacement, " + (string) (object) '\x008C' + " vous permettra de tous les prendre. Appuyez sur " + (string) (object) '\x0081' + " pour prendre un seul objet.\n\nAllez sur un autre emplacement et appuyez sur " + (string) (object) '\x008C' + " pour y placer l'objet.\n\nLorsque vous prenez un objet, vous pouvez passer de la section Équiper à la section Inventaire ; ou à une section coffre (ou tout autre stockage) ; et l'objet restera sur votre curseur.\n\nAppuyez sur " + (string) (object) '\x008A' + " pour mettre un objet directement dans la Poubelle.\n\nUn objet placé dans la Poubelle sera supprimé rapidement. Appuyez sur " + (string) (object) '\x0081' + " pour équiper les objets tels que les armures ou les accessoires dans des emplacements permettant une utilisation directe.",
      "<i>ÉQUIPER</i>\n\nLa section Équiper du menu Inventaire contient des emplacements pour les objets d'armure, de vanité, les accessoires, ainsi que les buffs et débuffs.\n\nUtilisez " + (object) '\x0084' + " pour vous déplacer dans les emplacements.\n\nLes objets dans les emplacements de Vanité apparaissent sur votre personnage mais ne confèrent ni statistiques, ni effets bonus.\n\nAppuyez sur " + (string) (object) '\x008C' + " pour prendre et placer des objets. Vous pouvez prendre un objet et passer des sections Équiper à Inventaire sans que l'objet ne quitte votre curseur.\n\nLes emplacements pour les buffs et débuffs actifs se trouvent au-dessus de l'avatar de votre personnage. Sélectionnez un buff ou débuff actif pour en savoir plus à son sujet. Appuyez sur " + (string) (object) '\x008C' + " pour annuler un buff ; les débuffs ne peuvent pas être annulés.",
      "<i>ARTISANAT</i>\n\nDans la section Artisanat, vous pouvez créer de nouveaux types d'objets en combinant ceux de votre inventaire comme ingrédients.\n\nLa section Artisanat fait partie du menu Inventaire qui s'ouvre en appuyant sur " + (object) '\x008B' + ". Allez à la section Artisanat en appuyant sur \x0082\x0083.\n\nPassez d'une catégorie d'objets à une autre en appuyant sur " + (string) (object) '\x0080' + " " + (string) (object) '\x0081' + ". Il y a six catégories : Structures, Outils, Armes, Armures, Consommables et Divers.\n\nUtilisez " + (string) (object) '\x0084' + " pour faire défiler les recettes d'artisanat.\n\nAppuyez sur " + (string) (object) '\x008C' + " pour fabriquer un objet à partir d'une recette et le placer dans votre inventaire.\n\nLes recettes d'objets sont affichées dans la liste verticale. Toute variante de cet objet de base figure dans la liste horizontale. Vous déverrouillerez davantage de recettes d'artisanat au fur et à mesure que vous collecterez des ingrédients exotiques ou créerez de nouveaux objets pour vos stations d'artisanat (par exemple, une table ou une enclume). Appuyez sur " + (string) (object) '\x008A' + " pour afficher uniquement les recettes que vous pouvez fabriquer actuellement ou celles que vous avez déverrouillées.\n\nLes ingrédients pour la recette choisie apparaissent dans la zone Ingrédients avec les objets de stations d'artisanat qui doivent se trouver aux alentours pour fabriquer cette recette. Appuyez sur " + (string) (object) '\x008B' + " pour entrer dans la zone Ingrédients (ou en sortir) afin d'en savoir plus sur chaque ingrédient.",
      "<i>LOGEMENT</i>\n\nConstruisez une maison avant la tombée de la nuit pour être en sécurité\n\nUne maison (ou chambre) est considérée comme <i>valide</i> si les murs font au moins 6 blocs de haut, et le plancher et le plafond 10 blocs de largeur. De plus, le fond doit être complètement recouvert de murs (par exemple, un mur en bois ou en terre). Pour finir, vous devez placer une source de lumière (par exemple, une torche), ainsi qu'une chaise et une table.\n\nVous pouvez modifier votre point d'apparition en plaçant un lit et en l'utilisant. Si vous trouvez un miroir magique, vous pouvez l'utiliser pour vous téléporter à votre point d'apparition.\n\nAu fur et à mesure de votre progression, des PNJ s'installeront dans votre maison si elle comporte des chambres libres et valides.\n\nDans le menu Inventaire, vous trouverez une section Logement qui vous permettra de gérer votre foyer. Ouvrez le menu Inventaire en appuyant sur " + (object) '\x008B' + ", puis appuyez sur \x0082\x0083 pour accéder à la section Logement.\n\nDans celle-ci, vous pouvez voir les PNJ qui vivent dans vos chambres. Appuyez sur " + (string) (object) '\x0084' + " pour sélectionner les différents PNJ et en savoir plus à leur sujet. Appuyez sur " + (string) (object) '\x008C' + " pour attribuer la chambre dans laquelle vous vous trouvez à un PNJ. Appuyez sur " + (string) (object) '\x008B' + " pour afficher ou masquer les drapeaux des chambres des PNJ dans le monde. Appuyez sur " + (string) (object) '\x008A' + " pour vérifier que vous vous trouvez dans un logement valide.",
      "<i>STOCKAGE ET VENDEURS</i>\n\nSi vous utilisez un objet de stockage dans le monde (comme un coffre) ou un PNJ vendeur (comme un marchand), cela ouvrira une section spéciale dans le menu Inventaire.\n\nDans une section d'objets de stockage, appuyez sur " + (object) '\x008C' + " pour prendre des objets et les placer. Vous pouvez prendre un objet et vous déplacer dans les sections Inventaire, Équiper et stockage, l'objet restera sur votre curseur.\n\nIl y a également trois raccourcis possibles :  <i>Piller Tout</i> déplace autant d'objets que possible vers votre inventaire ; <i>Déposer tout </i>déplace autant d'objets que possible de votre inventaire dans le stockage ; <i>Pile rapide</i> déplace uniquement les objets de votre inventaire correspondant aux piles d'objets déjà en stock.\n\nDans une section objets de vendeur, appuyez sur " + (string) (object) '\x008C' + " pour acheter un objet avec des pièces. Déplacez des objets de votre inventaire à la section d'objets de vendeur pour les vendre.",
      "<i>BUFFS ET DÉBUFFS</i>\n\nLes buffs sont les effets positifs sur l'état tels que l'invisibilité ou un animal de compagnie. Les débuffs sont les effets négatifs sur l'état tels que le saignement ou la maladie des potions.\n\nLes buffs et débuffs actifs sont affichés sous votre barre d'inventaire. La plupart ont une durée limitée. Vous pouvez en apprendre davantage à leur sujet dans la section Équiper du menu Inventaire. Depuis cette section, vous pouvez également annuler un buff en le sélectionnant et en appuyant sur " + (object) '\x008C' + ". Les débuffs ne peuvent pas être annulés.",
      "<i>MULTIJOUEUR</i>\n\nTerraria est un jeu multijoueur par défaut.\n\nL'écran partagé prend en charge jusqu'à 4 joueurs. Les joueurs locaux peuvent rejoindre la partie en connectant leurs manettes et en appuyant  " + (object) '\x0088' + " ou " + (string) (object) '\x008C' + " a tout moment.\n\nLes parties en ligne prennent en charge jusqu'à 8 joueurs. Lorsque vous commencez une partie en ligne, elle devient visible pour vos amis (à moins que vous n'ayez sélectionné \"Sur invitation seulement\"). De même, lorsque vos amis organisent des parties publiques, vous pourrez les voir et vous y joindre.\n\nPendant la partie, appuyez sur " + (string) (object) '\x0087' + " pour voir la liste des joueurs et leur emplacement sur la carte du monde. Depuis cet écran, vous pouvez également inviter des joueurs, voir les cartes de joueurs, basculer en mode Joueur contre Joueur (JcJ) ou choisir la couleur de votre équipe.\n\nLes joueurs qui activent le mode Joueur contre Joueur (JcJ) peuvent s'attaquer entre eux.\n\nLorsque les joueurs sélectionnent une couleur pour l'équipe, seuls leurs coéquipiers peuvent voir leur emplacement et leur santé. Les coéquipiers ne peuvent pas s'attaquer entre eux.",
      "<i>DONJON</i>\n\nIl existe un donjon dans chacun des mondes.\n\nN'entrez pas dans un donjon sans en avoir vaincu son gardien.\n\nCherchez un vieil homme et parlez-lui une fois qu'il fait nuit.\n\nSoyez prêt à tout.",
      "<i>MODE DIFFICILE</i>\n\nPour activer le mode Difficile, vous devez vaincre l'innommable horreur qui vit dans le monde des Enfers. Trouvez une poupée vaudou du guide et jetez-la dans la lave infernale pour invoquer la monstruosité.\n\nSi vous en sortez vainqueur, utilisez son trésor pour détruire les autels du démon.\n\nLe mode Difficile change définitivement le monde : de nouveaux environnements apparaissent, ainsi que de nouveaux ennemis, boss, objets et PNJ.\n\nLe mode Difficile est réservé aux guerriers les plus courageux.",
      "<i>BANNIR DES MONDES</i>\n\nSi vous trouvez du contenu offensant dans le monde d'un autre joueur, vous pouvez ajouter ce monde à votre Liste de mondes interdits. Pour ce faire, allez dans le menu Pause et appuyez sur " + (object) '\x0083' + ". Si vous essayez de vous joindre à ce monde plus tard, vous serez informé(e) que celui-ci est sur votre liste de mondes bannis et vous aurez la possibilité de le supprimer de la liste et continuer ou bien de quitter le monde."
    };
    public static string[] HTP_TEXT_IT = new string[14]
    {
      "<i>BASICS:</i>\n\nScava! Combatti! Esplora! Costruisci! Ogni Mondo di Terraria è unico, dalle isole fluttuanti nel cielo ai livelli più profondi del Sotterraneo. Spingiti all'estremità della terra e sconfiggi i perfidi boss che troverai durante la tua avventura. Il mondo è la tua tela.\n\nAbbatti gli alberi con l'ascia per raccogliere la legna. Uccidi gli Slime e raccogli la loro gelatina. Unisci la legna alla gelatina per creare delle torce.\n\nAvere le piattaforme di legno è utile quando esplori le caverne. Creale utilizzando la legna.\n\nUtilizza un piccone per estrarre i diversi tipi di minerali e fondili nella fornace per creare delle barre. Da utilizzare per creare armi e armature migliori. Alcune armi, come gli archi e le pistole, richiedono di munizioni che troverai nelle sezioni per le munizioni. È necessario avere il mana per le armi magiche.\n\nCerca i Cristalli di vita per aumentare il livello di vita e raccogli le Stelle cadenti per creare i Cristalli di mana.\n\nOh... e costruisci una casa prima che cali la notte. Ne avrai bisogno!",
      "<i>CREAZIONE PERSONAGGIO:</i>\n\nCrea un personaggio e personalizzalo a tuo piacimento!\n\nNella modalità <i>Normale,</i> quando il personaggio viene ucciso, perde solo le monete. Nella modalità <i>Difficile, </i>il personaggio perde tutti gli oggetti, mentre nella modalità <i>Hardcore </i>quando il personaggio muore, viene eliminato definitivamente. Questa modalità è raccomandata esclusivamente ai giocatori più esperti (e agli HARDCORE).\n\nGli oggetti di un personaggio rimangono su quel personaggio. Gli oggetti di un Mondo rimangono in quel Mondo.",
      "<i>COMANDI.</i>\n\nUtilizzare " + (object) '\x0084' + " per muoversi. Premere giù per passare da una piattaforma di legno all'altra.\n\nPremere " + (string) (object) '\x008C' + " per saltare.\n\nPremere " + (string) (object) '\x0081' + " per eseguire un'azione con l'oggetto in possesso: ad es. muovere un'ascia, posizionare una torcia, o bere una pozione.\n\nUtilizzare " + (string) (object) '\x0085' + " per puntare il cursore. Sono presenti due modalità Cursore " + (string) (object) '\x0085' + ". Premere " + (string) (object) '\x008F' + " per passare da una modalità all'altra.\n\n1) Premendo " + (string) (object) '\x0081' + " nella modalità Automatica, è possibile eseguire un'azione nella direzione del cursore.\n\n2) Nella modalità Manuale, il cursore funge da mouse. Premendo " + (string) (object) '\x0081' + ", è possibile eseguire un'azione nella posizione esatta del cursore.\n\nPremere " + (string) (object) '\x008D' + " per utilizzare un oggetto vicino o un PNG. Gli oggetti disponibili e i PNG sono evidenziati in giallo. Quando si è vicini, lampeggeranno e sarà possibile interagirvi.\n\nPremere " + (string) (object) '\x008A' + " per lasciare l'oggetto in uso.\n\nPuntare e premere " + (string) (object) '\x0080' + " per utilizzare un rampino o un oggetto simile (se presente nell'Inventario).\n\nÈ possibile premere " + (string) (object) '\x008E' + " come pulsante alternativo per saltare. I giocatori più esperti possono cambiare la modalità di lotta e alternare i pulsanti per saltare. È possibile eseguire questa azione dal menu Comandi.\n\nPremere " + (string) (object) '\x0087' + " per visualizzare la mappa del mondo e la lista giocatori.",
      "<i>HUD:</i>\n\nLa <i>barra dell'Inventario </i>si trova nella parte superiore dello schermo. L'oggetto di cui si è in possesso è evidenziato in giallo. È possibile scorrere gli oggetti, premendo \x0082\x0083. Per organizzare gli oggetti o visualizzare il resto dell'Inventario, premere " + (object) '\x008B' + ".\n\nInoltre, il livello di vita si trova nella parte superiore dello schermo. Ogni cuore costituisce 20 unità di vita.\n\nSe si è sott'acqua, il respiro restante è indicato sotto il livello di vita.\n\nIl mana apparirà sotto forma di stelle blu nella parte destra dello schermo, qualora in possesso. Ogni stella costituisce 20 mana.\n\nEventuali bonus e malus attivi sono indicati al di sotto della barra dell'Inventario, insieme alla loro durata restante. Per cancellare o ottenere maggiori informazioni sul bonus, consultare la sezione Equipaggiamento dal menu dell'Inventario.",
      "<i>INVENTARIO:</i>\n\nPremere " + (object) '\x008B' + " per accedere al menu dell'Inventario.\n\nIl menu dell'Inventario contiene diverse sezioni: Inventario, Equipaggiamento, Creazione Oggetti e Alloggio. Se è stata attivata una cassa o un venditore PNG, sarà presente una sezione dedicata a quest'ultimi.\n\nPassare da una sezione a un'altra, premendo \x0082\x0083.\n\nLa Barra dell'Inventario è la barra nella parte superiore delle sezioni degli oggetti del tuo Inventario.\n\nUtilizzare " + (string) (object) '\x0084' + " per passare da una sezione a un'altra.\n\nPremere " + (string) (object) '\x008C' + " per raccogliere un oggetto; se nella sezione è presente una pila di oggetti, sarà possibile raccoglierli tutti, premendo " + (string) (object) '\x008C' + " Premere " + (string) (object) '\x0081' + " per raccogliere un oggetto.\n\nSpostarsi in un'altra sezione e premere " + (string) (object) '\x008C' + " per posizionare l'oggetto raccolto.\n\nQuando si raccoglie un oggetto, è possibile passare dalla sezione Equipaggiamento a quella dell'Inventario o alla sezione cassa (o a un altro portaoggetti) e l'oggetto rimarrà sul cursore.\n\nPremere " + (string) (object) '\x008A' + " per spostare un oggetto direttamente nel Cestino.\n\nDopo un breve intervallo, l'oggetto presente nel Cestino verrà eliminato. Premere " + (string) (object) '\x0081' + " per equipaggiarsi di un'armatura o un accessorio direttamente da una sezione disponibile.",
      "<i>EQUIPAGGIAMENTO:</i>\n\nLa sezione Equipaggiamento del menu dell'Inventario contiene slot per le armature, oggetti di estetica, accessori, bonus e malus.\n\nUtilizzare " + (object) '\x0084' + " per spostarsi da uno slot all'altro.\n\nGli oggetti negli slot Estetica appaiono sul personaggio ma non forniscono bonus o effetti per le statistiche.\n\nPremere " + (string) (object) '\x008C' + " per raccogliere e posizionare gli oggetti. È possibile raccogliere un oggetto e spostarsi dalla sezione Equipaggiamento a quella dell'Inventario e l'oggetto rimarrà sul cursore.\n\nGli slot dei bonus/malus attivi si trovano al di sopra del proprio avatar. Selezionare il bonus o malus attivo per ottenere maggiori informazioni su di esso. Premere " + (string) (object) '\x008C' + " per annullare un bonus. I malus non possono essere annullati.",
      "<i>CREAZIONE OGGETTI:</i>\n\nNella sezione Creazione Oggetti è possibile creare nuovi tipi di oggetti, utilizzando come ingredienti gli elementi dell'Inventario.\n\nLa sezione Creazione Oggetti fa parte del menu dell'Inventario, che è possibile aprire, premendo " + (object) '\x008B' + ". Spostarsi nella sezione Creazione Oggetti premendo \x0082\x0083.\n\nSpostarsi da una categoria oggetti all'altra premendo " + (string) (object) '\x0080' + " " + (string) (object) '\x0081' + ". Esistono sei categorie: Strutture, Attrezzi, Armi, Armature, Accessori e Altro.\n\nUtilizzare " + (string) (object) '\x0084' + " per scorrere le formule per la creazione.\n\nPremere " + (string) (object) '\x008C' + " per creare un oggetto dalla formula per la creazione e posizionalo nell'Inventario.\n\nLe formule per gli oggetti sono indicate nella lista verticale. Tutte le modifiche riportate agli oggetti base saranno indicate nella lista orizzontale. Con l'ottenimento di ingredienti esotici o con la creazione di nuovi oggetti base per la creazione (es. banco da lavoro o incudine), si sbloccheranno altre formule per la creazione. Premere " + (string) (object) '\x008A' + " per spostarsi dalla modalità per visualizzare solo le formule che si possono creare, alla modalità per visualizzare tutte le formule sbloccate.\n\nGli ingredienti della formula utilizzata sono indicati nell'area Ingredienti, insieme a tutti gli oggetti base per la creazione, che devono trovarsi a disposizione all'interno del Mondo per creare formule. Premere " + (string) (object) '\x008B' + " per entrare (o uscire) dall'area Ingredienti per ottenere maggiori informazioni sui singoli ingredienti.",
      "<i>ALLOGGIO:</i>\n\nPer restare al sicuro, costruire un'abitazione prima che cali la notte.\n\nUn'abitazione (o stanza) è considerata <i>valida</i> se possiede muri laterali alti almeno 6 blocchi e un pavimento e soffitto larghi almeno 10 blocchi. Inoltre, lo sfondo deve essere interamente rivestito da muri (es. muri di legno o di terra). Infine, bisognerà posizionare una fonte di illuminazione (es. una torcia) e posizionare una sedia e un tavolo.\n\nÈ possibile modificare il punto di rigenerazione, posizionando e utilizzando il letto. Se si trova uno Specchio Magico, è possibile utilizzarlo per teletrasportarsi al punto di rigenerazione.\n\nMan mano che si procede, i PNG si trasferiranno all'interno dell'abitazione, se vi sono stanze vuote e valide in cui vivere.\n\nNel menu dell'Inventario è presente una sezione Alloggio, nella quale è possibile gestire la propria abitazione. Aprire il menu Inventario premendo " + (object) '\x008B' + ", e premere \x0082\x0083 per passare alla sezione Alloggio.\n\nNella sezione Alloggio è possibile visualizzare i PNG che vivono all'interno delle tue stanze. Premere " + (string) (object) '\x0084' + " per selezionare i diversi PNG e per ottenere maggiori informazioni su di essi. Premere " + (string) (object) '\x008C' + " per assegnare la stanza in cui ci si trova a un PNG. Premere " + (string) (object) '\x008B' + " per mostrare o nascondere le bandiere della stanza del PNG nel Mondo. Premere " + (string) (object) '\x008A' + " per controllare la validità dell'alloggio in cui ci si trova.",
      "<i>PORTAOGGETTI & VENDITORI:</i>\n\nSe nel Mondo si utilizza un portaoggetti (es. una cassa) o un venditore PNG (es. un mercante), nel menu dell'Inventario apparirà una sezione speciale.\n\nPremere " + (object) '\x008C' + " in una sezione portaoggetti per raccogliere e posizionare gli oggetti. È possibile raccogliere un oggetto e spostarsi dalla sezione Equipaggiamento a quella dell'Inventario e dei portaoggetti, e l'oggetto rimarrà sul cursore.\n\nInoltre, sono disponibili tre comandi per i portaoggetti: <i>Saccheggia Tutto</i> sposta quanti più oggetti possibile nell'Inventario; <i>Deposita Tutto</i> sposta quanti più oggetti possibile dall'Inventario al portaoggetti; <i>Raggruppamento Rapido</i> sposta solo gli oggetti dell'Inventario che corrispondono agli oggetti già accumulati nel portaoggetti.\n\nNella sezione Negozio, premere " + (string) (object) '\x008C' + " per acquistare un oggetto con le monete. Spostare gli oggetti dall'Inventario alla sezione Negozio per venderli.",
      "<i>BONUS & MALUS:</i>\n\nI bonus sono degli effetti positivi come l'Invisibilità o un'animale domestico. I malus sono degli effetti negativi come l'Avvelenamento da Pozione o il Sanguinamento.\n\nI bonus e i malus attivi sono indicati sotto la barra dell'Inventario. La maggior parte di essi possiede una durata limitata. È possibile ottenere maggiori informazioni nella sezione Equipaggiamento del menu dell'Inventario. Da qui, è inoltre possibile annullare un bonus, selezionandolo e premendo " + (object) '\x008C' + ". I malus non possono essere annullati.",
      "<i>MULTIGIOCATORE:</i>\n\nTerraria è un gioco di base multigiocatore.\n\nLo schermo condiviso supporta fino a 4 giocatori. I giocatori a livello locale possono unirsi al gioco, collegando i controller e premendo " + (object) '\x0088' + " o " + (string) (object) '\x008C' + " in qualsiasi momento.\n\nUna partita online può supportare fino a 8 giocatori. Quando si inizia una partita online, la partita sarà visibile a tutti gli amici (a meno che non si sia selezionato l'opzione 'Solo su invito'). Allo stesso modo, è possibile visualizzare e unirsi alla partita pubblica ospitata dagli amici.\n\nPremere " + (string) (object) '\x0087' + " durante la partita per visualizzare la lista dei giocatori e la loro posizione sulla Mappa del Mondo. Inoltre, è possibile invitare giocatori, visualizzare i profili, attivare la modalità Player vs Player (PvP) o scegliere il colore della propria squadra.\n\nNella modalità Player vs Player (PvP), i giocatori possono attaccarsi a vicenda.\n\nQuando i giocatori selezionano il colore della propria squadra, la loro posizione e la loro vita saranno visibili solo ai compagni di squadra. I compagni di squadra non possono attaccarsi fra di loro.",
      "<i>DUNGEON:</i>\n\nOgni Mondo contiene un Dungeon.\n\nNon entrare nel Dungeon senza aver prima sconfitto il guardiano.\n\nCerca un Vecchio e parlagli di notte.\n\nPreparati!",
      "<i>MODALITÀ HARD:</i>\n\nPer attivare la modalità Hard, è necessario sconfiggere l'orribile mostro che vive nel Sotterraneo. Trova la Bambola Voodoo della Guida e lanciala nella lava infernale per evocare il mostro.\n\nAlla sua sconfitta, utilizza il suo tesoro per distruggere gli Altari dei demoni.\n\nLa modalità Hard modifica definitivamente il Mondo; appariranno nuovi luoghi, nemici, boss, oggetti e PNG.\n\nLa modalità Hard è solo per i guerrieri più coraggiosi!",
      "<i>BLOCCARE I MONDI:</i>\nSe trovi del contenuto offensivo all'interno del Mondo di un altro giocatore, puoi scegliere di aggiungere quel Mondo alla tua lista dei Mondi bloccati. Per far ciò, entra nel Menu di Pausa e premi " + (object) '\x0083' + ". Se in futuro proverai ad entrare in quel Mondo, sarai notificato della sua presenza all'interno della tua lista dei Mondi bloccati e avrai inoltre la possibilità di scegliere se rimuoverlo dalla lista ed entrarci o no."
    };
    public static string[] HTP_TEXT_ES = new string[14]
    {
      "<i>INSTRUCCIONES BÁSICAS:</i>\n\n¡Excava! ¡Lucha! ¡Explora! ¡Construye! En Terraria cada mundo es único, desde las islas flotantes del cielo hasta los niveles más profundos del Inframundo. Vive aventuras en los confines de la tierra y derrota a los malvados jefes que se interpongan en tu camino. El mundo es tu lienzo.\n\nTala árboles con un hacha para conseguir leña. Elimina slimes y consigue sus geles. Combina madera y geles para crear antorchas.\n\nLas plataformas de madera son muy útiles a la hora de explorar cuevas. Constrúyelas con madera.\n\nUsa un pico para extraer los diferentes tipos de minerales del mundo y fúndelos en barras en la fundición. Úsalos para crear armas y armaduras mejores. Algunas armas, como los arcos y las pistolas, necesitan que coloques munición en las ranuras de munición. Las armas mágicas precisan maná.\n\nMantén los ojos abiertos en busca de Cristales de vida para mejorar tu salud y reúne Estrellas fugaces para crear Cristales de maná.\n\nAh, y construye una casa antes de que caiga la noche. La vas a necesitar...",
      "<i>CREACIÓN DE PERSONAJES:</i>\n\n¡Crea un personaje y personalízalo como quieras!\n\nEn el nivel de dificultad <i>Normal</i>, los personajes solo pierden monedas cuando son eliminados. En el nivel <i>Difícil</i>, los personajes pierden todos sus objetos. En el nivel <i>Hardcore</i>, si un personaje muere, es eliminado permanentemente. Este ajuste solo se recomienda a los jugadores más avanzados (¡y HARDCORE!).\n\nLos objetos de un personaje permanecen en ese personaje. Los objetos de un mundo se quedan en ese mundo.",
      "<i>CONTROLES:</i>\n\nUsa " + (object) '\x0084' + " para moverte. Pulsa abajo para dejarte caer por las plataformas de madera.\n\nPulsa " + (string) (object) '\x008C' + " para saltar.\n\nPulsa " + (string) (object) '\x0081' + " para realizar una acción con el objeto actual, como golpear con un hacha, colocar una antorcha o beber una poción.\n\nUsa " + (string) (object) '\x0085' + " para apuntar con el cursor. El cursor " + (string) (object) '\x0085' + " tiene dos modalidades. Pulsa " + (string) (object) '\x008F' + " para cambiar entre ellas.\n\n1) En el modo Automático, pulsa " + (string) (object) '\x0081' + " para realizar una acción en la dirección del cursor.\n\n2) En el modo Manual, el cursor actúa como un ratón. Pulsa " + (string) (object) '\x0081' + " para realizar una acción en la ubicación exacta del cursor.\n\nPulsa " + (string) (object) '\x008D' + " para interactuar con un objeto o PNJ cercano. Los objetos y PNJ con los que puedes interactuar se resaltan en amarillo. Cuando estás cerca, parpadearán y podrás interactuar con ellos.\n\nPulsa " + (string) (object) '\x008A' + " para soltar el objeto actual.\n\nApunta y pulsa " + (string) (object) '\x0080' + " para usar un garfio de escalada o similar (si tienes alguno en el inventario).\n\nPuedes pulsar " + (string) (object) '\x008E' + " como botón de salto alternativo. Los jugadores avanzados pueden cambiar los botones de agarre y salto alternativo, se puede hacer desde el menú de controles.\n\nPulsa " + (string) (object) '\x0087' + " para ver el mapamundi y la lista de jugadores.",
      "<i>PANEL DE INFORMACIÓN:</i>\n\nLa <i>barra de inventario</i> está en la parte superior de la pantalla. El objeto actual está resaltado en amarillo. Puedes navegar por los objetos pulsando \x0082\x0083. Para reorganizar los objetos o ver el resto del inventario, pulsa " + (object) '\x008B' + ".\n\nLa salud se muestra en la parte superior de la pantalla. Cada corazón representa 20 puntos de salud.\n\nSi estás bajo el agua, el aire restante se muestra debajo de la salud.\n\nSi tienes maná, aparecerá en forma de estrellas azules en la parte derecha de la pantalla. Cada estrella representa 20 puntos de maná.\n\nLos potenciadores o penalizadores activos se muestran en la barra de inventario, junto con la duración restante. Para cancelar un potenciador o informarte de sus funciones, entra en la sección Equipo del menú Inventario.",
      "<i>INVENTARIO:</i>\n\nPulsa " + (object) '\x008B' + " para acceder al menú Inventario.\n\nEl menú Inventario contiene varias secciones: Inventario, Equipo, Creación y Cobijo. Si has activado un cofre o un PNJ comerciante, también habrá una sección para el mismo.\n\nPasa de una sección a otra pulsando \x0082\x0083.\n\nLa barra del inventario es la fila superior de ranuras de objetos del inventario.\n\nUsa " + (string) (object) '\x0084' + " para moverte entre ranuras.\n\nPulsa " + (string) (object) '\x008C' + " para coger un objeto. Si hay varios objetos en la ranura, puedes cogerlos todos usando " + (string) (object) '\x008C' + ". Pulsa " + (string) (object) '\x0081' + " para coger un solo objeto.\n\nPasa a otra ranura y pulsa " + (string) (object) '\x008C' + " para colocar allí el objeto que has cogido.\n\nCuando coges un objeto puedes cambiar entre las secciones Equipo e Inventario, o una sección de cofre u otro espacio de almacenamiento; el objeto seguirá los movimientos del cursor.\n\nPulsa " + (string) (object) '\x008A' + " para poner un objeto directamente en la basura.\n\nLos objetos que estén en la basura serán eliminados después de un breve periodo. Pulsa " + (string) (object) '\x0081' + " para equipar objetos como armaduras o accesorios directamente en una ranura que puedas usar.",
      "<i>EQUIPO:</i>\n\nLa sección Equipo del menú Inventario contiene ranuras para armaduras, adornos, accesorios y potenciadores/penalizadores.\n\nUsa " + (object) '\x0084' + " para pasar de una ranura a otra.\n\nLos objetos de las ranuras de adornos no proporcionan bonificaciones de estado o efectos.\n\nPulsa " + (string) (object) '\x008C' + " para recoger y colocar objetos. Puedes recoger un objeto y moverlo entre las secciones Equipo e Inventario; el objeto seguirá los movimientos del cursor.\n\nLas ranuras de potenciadores/penalizadores activas aparecen sobre el avatar del personaje. Selecciona un potenciador o penalizador activo para obtener información sobre el mismo. Pulsa " + (string) (object) '\x008C' + " para cancelar un potenciador. Los penalizadores no se pueden cancelar.",
      "<i>CREACIÓN:</i>\n\nEn la sección Creación, puedes fabricar nuevos tipos de objetos combinando objetos del inventario como ingredientes.\n\nLa sección Creación es la parte del menú Inventario que puedes abrir pulsando " + (object) '\x008B' + ". Cambia a la sección Creación pulsando \x0082\x0083\n\nCambia entre categorías de objetos pulsando " + (string) (object) '\x0080' + " " + (string) (object) '\x0081' + ". Hay seis categorías: Estructuras, Herramientas, Armas, Armaduras, Consumibles y Varios.\n\nUsa " + (string) (object) '\x0084' + " para moverte entre las recetas de creación.\n\nPulsa " + (string) (object) '\x008C' + " para fabricar un objeto partiendo de una receta y ponerlo en el inventario.\n\nLas recetas de objetos se muestran en la lista vertical. Las variaciones de ese objeto base se muestran en una lista horizontal. Conforme vayas consiguiendo ingredientes exóticos y creando nuevos objetos para tu taller de creación (como una mesa o un yunque), se desbloquearán nuevas recetas. Pulsa " + (string) (object) '\x008A' + " para cambiar entre mostrar solo las recetas que puedes crear actualmente o mostrar todas las recetas que has desbloqueado.\n\nLos ingredientes de la receta actual se muestran en la zona de ingredientes, junto con los objetos del taller de creación que deben estar situados cerca para crear la receta. Pulsa " + (string) (object) '\x008B' + " para entrar (o salir) de la zona de ingredientes, donde podrás obtener más información sobre cada uno de ellos.",
      "<i>COBIJO:</i>\n\nDebes construir una casa antes de que caiga la noche para estar a salvo.\n\nUna casa o habitación se considera <i>válida</i> si tiene paredes laterales de como mínimo 6 bloques de alto y un techo de 10 bloques de ancho. Además, el fondo debe estar totalmente cubierto de muros (como muros de madera o de barro). Por último, debes poner una fuente de luz (como una antorcha), además de una silla y una mesa.\n\nPuedes cambiar el punto de reaparición colocando y usando una cama. Si encuentras un espejo mágico, puedes usarlo para teletransportarte de nuevo al punto de reaparición.\n\nConforme vayas progresando, los PNJ se mudarán a tu casa para vivir en ella si hay habitaciones válidas y vacías.\n\nPuedes gestionar tu casa mediante la sección Cobijo del menú Inventario. Abre el menú Inventario pulsando " + (object) '\x008B' + ", y pulsa \x0082\x0083 para acceder a la sección Cobijo.\n\nEn la sección Cobijo puedes ver a los PNJ viviendo en sus habitaciones. Pulsa " + (string) (object) '\x0084' + " para seleccionar diferentes PNJ y obtener información sobre ellos. Pulsa " + (string) (object) '\x008C' + " para asignar ese PNJ a la sala en la que estás. Pulsa " + (string) (object) '\x008B' + " para mostrar y ocultar las banderas de habitaciones de PNJ. Pulsa " + (string) (object) '\x008A' + " para comprobar si estás en un cobijo válido.",
      "<i>ALMACENAMIENTO Y COMERCIANTES:</i>\n\nAl interactuar con un objeto de almacenamiento (como un cofre) o con un PNJ comerciante (como un mercader), se abrirá una sección especial en el menú Inventario.\n\nPulsa " + (object) '\x008C' + " para coger y colocar objetos en la sección de almacenamiento. Puedes recoger un objeto y moverlo entre las secciones de Inventario, Equipo y Almacenamiento; el objeto seguirá los movimientos del cursor.\n\nHay tres accesos directos de almacenamiento disponibles: <i>Saquearlo todo</i> mueve tantos objetos como sea posible al inventario. <i>Depositarlo todo</i> mueve tantos objetos como sea posible del inventario al espacio de almacenamiento. <i>Apilamiento rápido</i> mueve solo los objetos del inventario que coinciden con objetos que ya están en el espacio de almacenamiento.\n\nEn una sección de objetos de comerciante, pulsa " + (string) (object) '\x008C' + " para comprar un objeto con monedas. Mueve los objetos del inventario a la sección de objetos del comerciante para venderlos.",
      "<i>POTENCIADORES Y PENALIZADORES:</i>\n\nLos potenciadores proporcionan efectos de estado positivos, como Invisibilidad o Mascotas. Los penalizadores son efectos de estado negativos como Hemorragia o Enfermedad de poción.\n\nLos potenciadores y penalizadores activos se muestran bajo la barra de inventario. La mayoría tienen efectos de duración limitada. Puedes obtener más información acerca de ellos en la sección Equipo del menú Inventario. Desde ahí también puedes cancelar un potenciador seleccionándolo y pulsando " + (object) '\x008C' + ". Los penalizadores no se pueden cancelar.",
      "<i>MULTIJUGADOR:</i>\n\nTerraria está diseñado especialmente para jugar con otros jugadores.\n\nEl modo de pantalla dividida es compatible con hasta 4 jugadores. Otros jugadores pueden unirse a una partida local conectando mandos y pulsando " + (object) '\x0088' + " o " + (string) (object) '\x008C' + " en cualquier momento.\n\nLas partidas online son compatibles con hasta 8 jugadores. Cuando inicias una partida online, la partida será visible para tus amigos (a menos que hayas seleccionado \"Solo por invitación\"). Del mismo modo, cuando tus amigos creen partidas públicas, serán visibles para ti.\n\nCuando estés en una partida, pulsa " + (string) (object) '\x0087' + " para ver una lista de jugadores y sus ubicaciones en el Mapamundi. Desde aquí también puedes invitar a jugadores, ver las tarjetas de jugador, activar o desactivar el modo Jugador Vs. Jugador o elegir el color de tu equipo.\n\nLos jugadores que activen el modo Jugador Vs. Jugador se pueden atacar entre ellos.\n\nAl elegir un color de equipo, la ubicación y la salud de un jugador solo serán visibles para sus compañeros de equipo. Los compañeros de equipo no se pueden atacar entre sí.",
      "<i>MAZMORRA:</i>\n\nCada mundo incluye una mazmorra.\n\nNo entres en la mazmorra sin derrotar antes a su guardián.\n\nBusca a un Anciano y habla con él por la noche.\n\nPrepárate.",
      "<i>MODO DIFÍCIL:</i>\n\nPara activar el modo Difícil, antes debes derrotar al innombrable horror que habita en el Inframundo. Encuentra un Muñeco vudú guía y lánzalo a la lava para invocar a la monstruosidad.\n\nSi lo derrotas, usa su tesoro para destruir los Altares demoníacos.\n\nEl modo Difícil cambia permanentemente el entorno: aparecen nuevos entornos, nuevos enemigos, jefes, objetos y PNJ.\n\nEl modo Difícil solo es para los guerreros más valientes.",
      "<i>CÓMO EXCLUIR MUNDOS:</i>\nSi el contenido de algún mundo de otro jugador te parece ofensivo, puedes añadir ese mundo a tu lista de Mundos Prohibidos. Para hacerlo, entra en el menú de Pausa y pulsa " + (object) '\x0083' + ". Si intentas unirte a ese mundo posteriormente, serás notificado de que está en tu lista de Mundos Prohibidos y tendrás la opción de eliminarlo de esa lista y entrar en el mundo o retroceder."
    };
    private const int SCROLL_SPEED = 4;
    private Terraria.UI parentUI;
    private static HowToPlayLayout[] pages;
    private int index;
    private short offsetY;

    private HowToPlayLayout SelectedPage
    {
      get
      {
        return UI.pages[this.index];
      }
    }

    public int Offset
    {
      get
      {
        return (int) this.offsetY;
      }
      set
      {
        this.offsetY = (short) MathHelper.Clamp((float) value, (float) this.SelectedPage.textblock.minOffsetY, 0.0f);
      }
    }

    static UI()
    {
    }

    public UI(Terraria.UI parentUI)
    {
      this.parentUI = parentUI;
      this.index = 0;
      this.offsetY = (short) 0;
    }

    public static UI Create(Terraria.UI parentUI)
    {
      return new UI(parentUI);
    }

    public void Update()
    {
      bool flag = false;
      if (this.parentUI.IsButtonTriggered(Buttons.X) && this.index > 0)
      {
        --this.index;
        flag = true;
      }
      else if (this.parentUI.IsButtonTriggered(Buttons.A) && this.index < UI.pages.Length - 1)
      {
        ++this.index;
        flag = true;
      }
      if (flag)
      {
        this.offsetY = (short) 0;
        Main.PlaySound(12);
      }
      else
      {
        if (!this.SelectedPage.textblock.isScrollable)
          return;
        if (this.parentUI.IsDownButtonDown())
        {
          this.Offset -= 4;
        }
        else
        {
          if (!this.parentUI.IsUpButtonDown())
            return;
          this.Offset += 4;
        }
      }
    }

    public void Draw()
    {
      this.SelectedPage.Draw(this.parentUI.view.SAFE_AREA_OFFSET_L, this.parentUI.view.SAFE_AREA_OFFSET_T, (int) this.offsetY);
    }

    public void ControlDescription(StringBuilder strBuilder)
    {
      if (this.index < UI.pages.Length - 1)
      {
        strBuilder.Append(Lang.controls(Lang.CONTROLS.NEXT_PAGE));
        strBuilder.Append(' ');
      }
      if (this.index > 0)
      {
        strBuilder.Append(Lang.controls(Lang.CONTROLS.PREVIOUS_PAGE));
        strBuilder.Append(' ');
      }
      if (this.SelectedPage.textblock.isScrollable)
      {
        strBuilder.Append(Lang.controls(Lang.CONTROLS.SCROLL_TEXT));
        strBuilder.Append(' ');
      }
      strBuilder.Append(Lang.controls(Lang.CONTROLS.BACK));
    }

    public static void GenerateCache(GraphicsDevice graphicsDevice)
    {
      string[] strArray1 = UI.HTP_TEXT_EN;
      switch (Lang.lang)
      {
        case 2:
          strArray1 = UI.HTP_TEXT_DE;
          break;
        case 3:
          strArray1 = UI.HTP_TEXT_IT;
          break;
        case 4:
          strArray1 = UI.HTP_TEXT_FR;
          break;
        case 5:
          strArray1 = UI.HTP_TEXT_ES;
          break;
      }
      int num1 = 0;
      HowToPlayLayout[] howToPlayLayoutArray1 = new HowToPlayLayout[14];
      HowToPlayLayout[] howToPlayLayoutArray2 = howToPlayLayoutArray1;
      int index1 = 0;
      string[] strArray2 = strArray1;
      int index2 = num1;
      int num2 = 1;
      int num3 = index2 + num2;
      HowToPlayLayout howToPlayLayout1 = HowToPlayLayout.StackedLayout(strArray2[index2], 700, 260, Assets.HOWTO_LOGO, 20);
      howToPlayLayoutArray2[index1] = howToPlayLayout1;
      HowToPlayLayout[] howToPlayLayoutArray3 = howToPlayLayoutArray1;
      int index3 = 1;
      string[] strArray3 = strArray1;
      int index4 = num3;
      int num4 = 1;
      int num5 = index4 + num4;
      HowToPlayLayout howToPlayLayout2 = HowToPlayLayout.StackedLayout(strArray3[index4], 700, 260, Assets.HOWTO_LOGO, 20);
      howToPlayLayoutArray3[index3] = howToPlayLayout2;
      HowToPlayLayout[] howToPlayLayoutArray4 = howToPlayLayoutArray1;
      int index5 = 2;
      string[] strArray4 = strArray1;
      int index6 = num5;
      int num6 = 1;
      int num7 = index6 + num6;
      HowToPlayLayout howToPlayLayout3 = HowToPlayLayout.SideBySideLayout(strArray4[index6], 500, Assets.HOWTO_MOVEMENT, 20);
      howToPlayLayoutArray4[index5] = howToPlayLayout3;
      HowToPlayLayout[] howToPlayLayoutArray5 = howToPlayLayoutArray1;
      int index7 = 3;
      string[] strArray5 = strArray1;
      int index8 = num7;
      int num8 = 1;
      int num9 = index8 + num8;
      HowToPlayLayout howToPlayLayout4 = HowToPlayLayout.StackedLayout(strArray5[index8], 700, 260, Assets.HOWTO_HOTBAR2, 20);
      howToPlayLayoutArray5[index7] = howToPlayLayout4;
      HowToPlayLayout[] howToPlayLayoutArray6 = howToPlayLayoutArray1;
      int index9 = 4;
      string[] strArray6 = strArray1;
      int index10 = num9;
      int num10 = 1;
      int num11 = index10 + num10;
      HowToPlayLayout howToPlayLayout5 = HowToPlayLayout.SideBySideLayout(strArray6[index10], 500, Assets.HOWTO_INVENTORY, 20);
      howToPlayLayoutArray6[index9] = howToPlayLayout5;
      HowToPlayLayout[] howToPlayLayoutArray7 = howToPlayLayoutArray1;
      int index11 = 5;
      string[] strArray7 = strArray1;
      int index12 = num11;
      int num12 = 1;
      int num13 = index12 + num12;
      HowToPlayLayout howToPlayLayout6 = HowToPlayLayout.TextOnlyLayout(strArray7[index12], 700);
      howToPlayLayoutArray7[index11] = howToPlayLayout6;
      HowToPlayLayout[] howToPlayLayoutArray8 = howToPlayLayoutArray1;
      int index13 = 6;
      string[] strArray8 = strArray1;
      int index14 = num13;
      int num14 = 1;
      int num15 = index14 + num14;
      HowToPlayLayout howToPlayLayout7 = HowToPlayLayout.TextOnlyLayout(strArray8[index14], 700);
      howToPlayLayoutArray8[index13] = howToPlayLayout7;
      HowToPlayLayout[] howToPlayLayoutArray9 = howToPlayLayoutArray1;
      int index15 = 7;
      string[] strArray9 = strArray1;
      int index16 = num15;
      int num16 = 1;
      int num17 = index16 + num16;
      HowToPlayLayout howToPlayLayout8 = HowToPlayLayout.TextOnlyLayout(strArray9[index16], 700);
      howToPlayLayoutArray9[index15] = howToPlayLayout8;
      HowToPlayLayout[] howToPlayLayoutArray10 = howToPlayLayoutArray1;
      int index17 = 8;
      string[] strArray10 = strArray1;
      int index18 = num17;
      int num18 = 1;
      int num19 = index18 + num18;
      HowToPlayLayout howToPlayLayout9 = HowToPlayLayout.TextOnlyLayout(strArray10[index18], 700);
      howToPlayLayoutArray10[index17] = howToPlayLayout9;
      HowToPlayLayout[] howToPlayLayoutArray11 = howToPlayLayoutArray1;
      int index19 = 9;
      string[] strArray11 = strArray1;
      int index20 = num19;
      int num20 = 1;
      int num21 = index20 + num20;
      HowToPlayLayout howToPlayLayout10 = HowToPlayLayout.StackedLayout(strArray11[index20], 700, 300, Assets.HOWTO_DEBUFF, 20);
      howToPlayLayoutArray11[index19] = howToPlayLayout10;
      HowToPlayLayout[] howToPlayLayoutArray12 = howToPlayLayoutArray1;
      int index21 = 10;
      string[] strArray12 = strArray1;
      int index22 = num21;
      int num22 = 1;
      int num23 = index22 + num22;
      HowToPlayLayout howToPlayLayout11 = HowToPlayLayout.TextOnlyLayout(strArray12[index22], 700);
      howToPlayLayoutArray12[index21] = howToPlayLayout11;
      HowToPlayLayout[] howToPlayLayoutArray13 = howToPlayLayoutArray1;
      int index23 = 11;
      string[] strArray13 = strArray1;
      int index24 = num23;
      int num24 = 1;
      int num25 = index24 + num24;
      HowToPlayLayout howToPlayLayout12 = HowToPlayLayout.TextOnlyLayout(strArray13[index24], 700);
      howToPlayLayoutArray13[index23] = howToPlayLayout12;
      HowToPlayLayout[] howToPlayLayoutArray14 = howToPlayLayoutArray1;
      int index25 = 12;
      string[] strArray14 = strArray1;
      int index26 = num25;
      int num26 = 1;
      int num27 = index26 + num26;
      HowToPlayLayout howToPlayLayout13 = HowToPlayLayout.TextOnlyLayout(strArray14[index26], 700);
      howToPlayLayoutArray14[index25] = howToPlayLayout13;
      HowToPlayLayout[] howToPlayLayoutArray15 = howToPlayLayoutArray1;
      int index27 = 13;
      string[] strArray15 = strArray1;
      int index28 = num27;
      int num28 = 1;
      int num29 = index28 + num28;
      HowToPlayLayout howToPlayLayout14 = HowToPlayLayout.TextOnlyLayout(strArray15[index28], 700);
      howToPlayLayoutArray15[index27] = howToPlayLayout14;
      UI.pages = howToPlayLayoutArray1;
      foreach (HowToPlayLayout howToPlayLayout15 in UI.pages)
        howToPlayLayout15.GenerateCache(graphicsDevice);
    }
  }
}
